scene_extraction_task:
  description: >
    Analyze the provided text answering the following user query: '{topic}'. Identify a scene that can be clearly depicted in an image.
    Ensure the scene is illustrative and easy to describe for image creation.
    Text: {text}
  expected_output: >
    A concise description of a single scene suitable for image generation, highlighting key visual elements.
  agent: scene_extractor

image_prompt_task:
  description: >
    Craft a detailed, realistic prompt for generating an image based on the scene extracted by the previous agent.
    The prompt should be clear, visually descriptive, and suitable for use with image generation tools.
  expected_output: >
    A well-structured image prompt that accurately conveys the scene and its visual details for image generation.
  agent: image_prompt_generator

image_creation_task:
  description: >
    Use the provided image prompt and tools to generate a realistic image that explains the topic.
    Ensure the image is engaging and accessible for a wide audience.
    Save the image in a folder named 'output'.
    The image generation tool requires ONLY two parameters: the prompt and the path to save the image.
  expected_output: >
    A generated image file (or link) along with a brief description of how the image represents the given topic.
  context: 
    - image_prompt_task
  agent: image_creator