parse_docs:
  description: >
    Load and parse the given Sphinx docs to extract structured project information.
  expected_output: >
    A structured knowledge base (JSON) of the project documentation.
  agent: doc_parser
 
parse_template:
  description: >
    Parse the AI Act template using the specified tool.
  expected_output: >
    A JSON schema with all AI Act fields, nested as per HTML hierarchy.
  agent: template_parser
 
generate_ai_act:
  description: >
    Generate a draft AI Act compliance document by filling the schema using project documentation. 
    Missing fields should be filled with '[PLACEHOLDER, <description>]'.
    Do not make assumptions that are not based on the documentation you received.
  expected_output: >
    Draft AI Act document (Markdown/JSON) with project-specific details and placeholders.
  agent: act_document_generator
  context:
    - parse_docs
    - parse_template

fill_placeholders:
  description: >
    Use RAG to search AI Act documentation and regulatory guidance to fill in any placeholder values remaining in the draft AI Act document.
    Use the placholder description as a guide.
    Search for relevant information to replace placeholders with accurate, regulation-compliant content.
    When the retrieved content is not relevant enough, leave the placeholder.
  expected_output: >
    Enhanced AI Act document with placeholders filled using RAG-retrieved information, maintaining original content where placeholders could not be improved.
    Generate a Markdown document.
  agent: rag_placeholder_filler
  context:
    - generate_ai_act
